# Generated by Django 2.1 on 2018-08-30 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_users_is_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
